#! /bin/env python

import math

import matplotlib.pyplot as plt
import typer


DEFAULT_WIDTH = 345.0 * 0.95 # document width in points
DEFAULT_HEIGHT = DEFAULT_WIDTH * 0.8

PEAK_SCALAR = 2
PEAK_VECTOR = 16
MAIN_MEMORY_BANDWIDTH = 30
CACHE_BANDWIDTH = 100

MIN_ARITHMETIC_INTENSITY = 1/1064
MAX_ARITHMETIC_INTENSITY = 16
MIN_THROUGHPUT = 1/100
MAX_THROUGHPUT = 80


plt.style.use("report")


def inches_to_pts(inches):
    return inches * 72


def pts_to_inches(pts):
    return pts / 72


def plot_line(ax, xmin, xmax, ymin, ymax):
    ax.plot(
        [xmin, xmax],
        [ymin, ymax],
        color="black",
        solid_capstyle="round",
    )


def log_diff(low, high):
    return math.log(high) - math.log(low)


def compute_angle(xmin, xmax, ymin, ymax, width, height):
    opp = log_diff(ymin, ymax) / log_diff(MIN_THROUGHPUT, MAX_THROUGHPUT) * height
    adj = log_diff(xmin, xmax) / log_diff(MIN_ARITHMETIC_INTENSITY, MAX_ARITHMETIC_INTENSITY) * width
    return math.degrees(math.atan(opp/adj))


def main(
    outfile: str = typer.Option("", "-o"),
    width: int = DEFAULT_WIDTH,
    height: int = DEFAULT_HEIGHT,
):
    fig, ax = plt.subplots(
        1, 1,
        figsize=(pts_to_inches(width), pts_to_inches(height))
    )

    ax.set_xlabel("Arithmetic intensity (FLOPs/byte)")
    ax.set_ylabel("Arithmetic throughput (FLOPs/sec)")

    ax.set_xscale("log")
    ax.set_yscale("log")

    ax.set_xlim(MIN_ARITHMETIC_INTENSITY, MAX_ARITHMETIC_INTENSITY)
    ax.set_ylim(MIN_THROUGHPUT, MAX_THROUGHPUT)

    # hide tick labels
    ax.set_xticklabels([""]*len(ax.get_xticks()))
    ax.set_yticklabels([""]*len(ax.get_yticks()))

    # cache bandwidth
    xmin = MIN_ARITHMETIC_INTENSITY
    ymin = MIN_ARITHMETIC_INTENSITY * CACHE_BANDWIDTH
    xmax = PEAK_VECTOR / CACHE_BANDWIDTH
    ymax = PEAK_VECTOR
    plot_line(ax, xmin, xmax, ymin, ymax)

    ax.annotate(
        "Peak cache bandwidth",
        (MIN_ARITHMETIC_INTENSITY, ymin),
        (12, 15),
        textcoords="offset points",
        rotation=compute_angle(xmin, xmax, ymin, ymax, width, height),
        rotation_mode="anchor",
        verticalalignment="bottom",
    )

    # main memory bandwidth
    xmin = MIN_ARITHMETIC_INTENSITY
    ymin = MIN_ARITHMETIC_INTENSITY * MAIN_MEMORY_BANDWIDTH
    xmax = PEAK_VECTOR / MAIN_MEMORY_BANDWIDTH
    ymax = PEAK_VECTOR
    plot_line(ax, xmin, xmax, ymin, ymax)
    ax.annotate(
        "Peak main memory bandwidth",
        (MIN_ARITHMETIC_INTENSITY, ymin),
        (12, 12),
        textcoords="offset points",
        rotation=compute_angle(xmin, xmax, ymin, ymax, width, height),
        rotation_mode="anchor",
        verticalalignment="bottom",
    )

    # peak scalar throughput
    xmin = PEAK_SCALAR / CACHE_BANDWIDTH
    xmax = MAX_ARITHMETIC_INTENSITY
    ymin = ymax = PEAK_SCALAR
    plot_line(ax, xmin, xmax, ymin, ymax)
    ax.annotate(
        "Peak scalar throughput",
        (MAX_ARITHMETIC_INTENSITY, ymax),
        (-90, 2),
        textcoords="offset points",
        verticalalignment="bottom",
    )

    # peak vector throughput
    xmin = PEAK_VECTOR / CACHE_BANDWIDTH
    xmax = MAX_ARITHMETIC_INTENSITY
    ymin = ymax = PEAK_VECTOR
    plot_line(ax, xmin, xmax, ymin, ymax)
    ax.annotate(
        "Peak vector throughput",
        (MAX_ARITHMETIC_INTENSITY, ymax),
        (-90, 2),
        textcoords="offset points",
        verticalalignment="bottom",
    )

    # plot A
    x = 1 / 256
    y = 1/20
    ax.scatter([x], [y], color="red")
    ax.annotate(
        "A", (x, y), (6, -6), textcoords="offset points",
        verticalalignment="center", horizontalalignment="center"
    )

    # plot B
    x = 0.7
    y = 1/8
    ax.scatter([x], [y], color="red")
    ax.annotate(
        "B", (x, y), (6, -6), textcoords="offset points",
        verticalalignment="center", horizontalalignment="center"
    )

    # plot C
    x = 4
    y = 8
    ax.scatter([x], [y], color="red")
    ax.annotate(
        "C", (x, y), (6, -6), textcoords="offset points",
        verticalalignment="center", horizontalalignment="center"
    )

    if outfile:
        fig.savefig(outfile, backend="pgf")
    else:
        plt.show()


if __name__ == "__main__":
    typer.run(main)
